"""adicionei um id ao usuario para fazer a conexão com animal

Revision ID: 37db48fab318
Revises: f4b9c316743e
Create Date: 2021-10-06 11:37:28.517080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37db48fab318'
down_revision = 'f4b9c316743e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_animal_dono_usuario', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_animal_dono_usuario'), 'usuario', ['dono'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animal_dono_usuario'), type_='foreignkey')
        batch_op.create_foreign_key('fk_animal_dono_usuario', 'usuario', ['dono'], ['nome'])

    # ### end Alembic commands ###
