"""Corrigindo

Revision ID: ae7d64062f30
Revises: 
Create Date: 2021-10-06 19:44:45.067012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7d64062f30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dono', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dono'], ['usuario.id'], name=op.f('fk_animal_dono_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    op.drop_table('usuario')
    # ### end Alembic commands ###
