"""criação do banco

Revision ID: f69e028e6b35
Revises: 
Create Date: 2021-10-05 16:28:45.753395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69e028e6b35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', 'nome', name=op.f('pk_usuario'))
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dono', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dono'], ['usuario.nome'], name=op.f('fk_animal_dono_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    op.drop_table('usuario')
    # ### end Alembic commands ###
